<script>
  import { onMount } from "svelte";
  import { SDK_V3 } from "$lib/sdk/index";

  let hydrated = false;

  onMount(async () => {
    SDK_V3.configure({
      apiBaseUrl: "http://localhost:5173/api/v2/public/",
      jwtToken: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzaXRlSWQiOiIzY2M0MGJiYy0yYjcxLTRhZGMtOTYwNC0wY2U1MjY1ZjExNmMiLCJkb21haW4iOiJsb2NhbGhvc3Q6NTE3MyIsInBlcm1pc3Npb25zIjpbInJlYWQ6Y29udGVudCJdLCJpYXQiOjE3NjMwNTA3ODQsImV4cCI6MTc5NDU4Njc4NH0.gEo8liJIL-Snf02nZZfPct0iKyhfXu96jTgPDK8z8yI"
    })
    SDK_V3.run();
    
    hydrated = true;
  });
</script>

<style>
  :root {
    --supa-bg: #1c1c1c;
    --supa-card: #232323;
    --supa-border: #333333;
    --supa-text-main: #ededed;
    --supa-text-muted: #888888;
    --supa-primary: #3ecf8e; /* Supabase Green */
    --supa-font: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
  }

  body {
    background-color: var(--supa-bg);
    color: var(--supa-text-main);
    font-family: var(--supa-font);
    margin: 0;
    line-height: 1.6;
  }

  /* UTILITIES */
  .container {
    max-width: 1200px;
    margin: 0 auto;
    padding: 0 20px;
  }

  .section-spacer {
    padding: 80px 0;
  }

  /* 1. HERO SECTION STYLING */
  .hero-wrapper {
    display: flex;
    flex-direction: column;
    align-items: center;
    text-align: center;
    padding: 100px 0 60px;
    background: radial-gradient(circle at 50% 10%, rgba(62, 207, 142, 0.15), transparent 40%);
  }

  .hero-title {
    font-size: 3.5rem;
    font-weight: 800;
    letter-spacing: -0.02em;
    margin-bottom: 20px;
    background: linear-gradient(to right, #fff, #aaa);
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
  }

  .hero-subtitle {
    font-size: 1.25rem;
    color: var(--supa-text-muted);
    max-width: 600px;
    margin-bottom: 40px;
  }

  /* 2. AUTO-GENERATED GRIDS (Walkdown Styling) */
  /* This forces the 'foundy' generated children into a grid */
  .foundy-grid-target {
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(300px, 1fr));
    gap: 24px;
    margin-top: 40px;
  }

  /* We target the direct children generated by the engine */
  .foundy-grid-target > * {
    background: var(--supa-card);
    border: 1px solid var(--supa-border);
    border-radius: 8px;
    padding: 24px;
    transition: transform 0.2s ease, border-color 0.2s ease;
    display: flex;
    flex-direction: column;
    align-items: flex-start;
  }

  .foundy-grid-target > *:hover {
    border-color: var(--supa-primary);
    transform: translateY(-2px);
  }

  /* Target Headers inside generated cards */
  .foundy-grid-target h1, 
  .foundy-grid-target h2, 
  .foundy-grid-target h3 {
    font-size: 1.5rem;
    margin-top: 0;
    color: var(--supa-text-main);
  }

  /* Target Images inside generated cards */
  .foundy-grid-target img {
    width: 100%;
    height: 200px;
    object-fit: cover;
    border-radius: 4px;
    margin-bottom: 15px;
    background-color: #000;
  }

  /* 3. LOGO WALL (Featured) */
  .logo-wall {
    display: flex;
    flex-wrap: wrap;
    justify-content: center;
    gap: 40px;
    opacity: 0.6;
    margin-top: 20px;
    filter: grayscale(100%);
  }
  
  /* Assume the walkdown creates divs for companies */
  .logo-wall > * {
    display: flex;
    align-items: center;
  }
  
  .logo-wall img {
    max-height: 40px;
  }

</style>

<section class="hero-wrapper container">
  <h1 class="hero-title" data-foundy="homepage:<hero<title>>">
    </h1>
  
  <div class="hero-subtitle" data-foundy="homepage:<hero<subtitle>>">
    </div>

  <button style="background: var(--supa-primary); color: #000; border: none; padding: 12px 24px; font-weight: 600; border-radius: 6px; cursor: pointer; font-size: 1rem;">
    Start Building
  </button>

  <div style="margin-top: 40px;">
     <img data-foundy="homepage:<hero<logo>>" style="height: 60px; width: auto;" />
  </div>
</section>

<section class="container section-spacer" style="border-bottom: 1px solid var(--supa-border);">
  <div style="text-align: center; margin-bottom: 30px; color: var(--supa-text-muted); font-size: 0.9rem; text-transform: uppercase; letter-spacing: 1px;">
    Trusted by top companies
  </div>
  
  <div class="logo-wall" data-foundy="homepage:<featured>">
  </div>
</section>

<section class="container section-spacer">
  <div style="text-align: center;">
    <h2 style="font-size: 2.5rem; margin-bottom: 10px;">Simple Pricing</h2>
    <p style="color: var(--supa-text-muted);">Predictable scaling for your project.</p>
  </div>

  <div class="foundy-grid-target" data-foundy="homepage:<pricing>">
     </div>
</section>

<section class="container section-spacer">
  <div style="display: flex; justify-content: space-between; align-items: flex-end; margin-bottom: 20px;">
    <div>
      <h2 style="font-size: 2rem; margin: 0;">Latest Updates</h2>
    </div>
    <a href="/blog" style="color: var(--supa-primary); text-decoration: none;">View all posts &rarr;</a>
  </div>

  <div class="foundy-grid-target" data-foundy="post::0-3">
    </div>
</section>